apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-service-service
  labels:
    run: kafka-broker-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 9092
      protocol: TCP
      name: kafkabroker
      targetPort: 9092
  selector:
    app: kafka-broker-service