apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth-service-virtual
spec:
  hosts:
    - "*"
  gateways:
    - microecom-gateway
  http:
    - name: "rest-v1-routes"
      match:
        - uri:
            prefix: /rest/V1/user
      route:
        - destination:
            host: auth-service-service
            port:
              number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service-container-kube
          image: auth-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: debug
              containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
  labels:
    run: auth-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: 8080
    - port: 5005
      protocol: TCP
      name: debug
      targetPort: 5005
  selector:
    app: auth-service
