apiVersion: v1
kind: Service
metadata:
  name: order-event-service-service
  labels:
    run: order-event-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 5013
      protocol: TCP
      name: debug
      targetPort: 5013
  selector:
    app: order-event-service