apiVersion: v1
kind: Service
metadata:
  name: order-db-service
  labels:
    run: order-db-service
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      name: pgsql
  selector:
    app: order-db