apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper-service-service
  labels:
    run: kafka-zookeeper-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      protocol: TCP
      name: http
      targetPort: 8080
    - port: 2181
      protocol: TCP
      name: zookeeper
      targetPort: 2181
  selector:
    app: kafka-zookeeper-service