apiVersion: v1
kind: Service
metadata:
  name: catalog-http-service-service
  labels:
    run: catalog-http-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      protocol: TCP
      name: http
      targetPort: 8080
    - port: 5007
      protocol: TCP
      name: debug
      targetPort: 5007
  selector:
    app: catalog-http-service