apiVersion: v1
kind: Service
metadata:
  name: catalog-db-service
  labels:
    run: catalog-db-service
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      name: pgsql
  selector:
    app: catalog-db