apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inventory-http-service-virtual
spec:
  hosts:
    - "*"
  gateways:
    - microecom-gateway
  http:
    - name: "inventory-rest-v1-routes"
      match:
        - uri:
            prefix: /rest/V1/stock
      route:
        - destination:
            host: inventory-http-service-service
            port:
              number: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-http-service-deployment
  labels:
    app: inventory-http-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-http-service
  template:
    metadata:
      labels:
        app: inventory-http-service
    spec:
      containers:
        - name: inventory-http-service-container-kube
          image: inventory-http-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: debug
              containerPort: 5008
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-http-service-service
  labels:
    run: inventory-http-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      protocol: TCP
      name: http
      targetPort: 8080
    - port: 5008
      protocol: TCP
      name: debug
      targetPort: 5008
  selector:
    app: inventory-http-service
