apiVersion: v1
kind: Service
metadata:
  name: inventory-http-service-service
  labels:
    run: inventory-http-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      protocol: TCP
      name: http
      targetPort: 8080
    - port: 5008
      protocol: TCP
      name: debug
      targetPort: 5008
  selector:
    app: inventory-http-service