apiVersion: v1
kind: Service
metadata:
  name: grpc-auth-debug
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      protocol: TCP
      name: debug
      targetPort: 5005
  selector:
    app: auth-grpc-service
