apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: auth-grpc-service-destinations
spec:
  host: grpc-auth
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-grpc-service-deployment
  labels:
    app: auth-grpc-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-grpc-service
  template:
    metadata:
      labels:
        app: auth-grpc-service
    spec:
      containers:
        - name: auth-grpc-service-container-kube
          image: auth-grpc-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 8080
            - name: debug
              containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-auth
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: grpc
      targetPort: 8080
  selector:
    app: auth-grpc-service
