apiVersion: v1
kind: Service
metadata:
  name: catalog-event-service-service
  labels:
    run: catalog-event-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 5010
      protocol: TCP
      name: debug
      targetPort: 5010
  selector:
    app: catalog-event-service