apiVersion: v1
kind: Service
metadata:
  name: inventory-event-service-service
  labels:
    run: inventory-event-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 5014
      protocol: TCP
      name: debug
      targetPort: 5014
  selector:
    app: inventory-event-service