apiVersion: apps/v1
kind: Deployment
metadata:
  name: phptest1-deployment
  labels:
    app: phptest1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phptest1
  template:
    metadata:
      labels:
        app: phptest1
    spec:
      containers:
        - name: php-test-app-container-kube
          image: php-test-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
            - name: ssh
              containerPort: 22