apiVersion: v1
kind: Service
metadata:
  name: php-service2
  labels:
    run: php-service2
spec:
  type: LoadBalancer
  ports:
    - port: 81
      protocol: TCP
      targetPort: 80
  selector:
    app: phptest2