apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    run: web-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
    - port: 22221
      protocol: TCP
      targetPort: 22
      name: ssh
  selector:
    app: phptest1