apiVersion: v1
kind: Service
metadata:
  name: order-http-service-service
  labels:
    run: order-http-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 8085
      protocol: TCP
      name: http
      targetPort: 8080
    - port: 5012
      protocol: TCP
      name: debug
      targetPort: 5012
  selector:
    app: order-http-service