apiVersion: v1
kind: Service
metadata:
  name: payment-http-service-service
  labels:
    run: payment-http-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 8084
      protocol: TCP
      name: http
      targetPort: 8080
    - port: 5011
      protocol: TCP
      name: debug
      targetPort: 5011
  selector:
    app: payment-http-service