apiVersion: v1
kind: Service
metadata:
  name: kafka-admin-service-service
  labels:
    run: kafka-admin-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 9119
      protocol: TCP
      name: http
      targetPort: 9000
  selector:
    app: kafka-admin-service