apiVersion: v1
kind: Service
metadata:
  name: http-customer-debug
spec:
  type: LoadBalancer
  ports:
    - port: 5002
      protocol: TCP
      name: debug
      targetPort: 5005
  selector:
    app: customer-http-service