apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-http-service-virtual
spec:
  hosts:
    - "*"
  gateways:
    - microecom-gateway
  http:
    - name: "customer-rest-v1-routes"
      match:
        - uri:
            prefix: /rest/V1/address
        - uri:
            prefix: /rest/V1/customer
      route:
        - destination:
            host: http-customer
            port:
              number: 8080
      timeout: 10s
      retries:
        attempts: 8
        retryOn: "5xx,gateway-error,connect-failure,reset"
        perTryTimeout: 1s
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: customer-http-service-destinations
spec:
  host: http-customer
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
    outlierDetection:
      consecutiveGatewayErrors: 100
      baseEjectionTime: 1m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-http-service-deployment
  labels:
    app: customer-http-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: customer-http-service
  template:
    metadata:
      labels:
        app: customer-http-service
    spec:
      containers:
        - name: customer-http-service-container-kube
          image: customer-http-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: debug
              containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: http-customer
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: 8080
  selector:
    app: customer-http-service
