apiVersion: v1
kind: Service
metadata:
  name: db-customer
  labels:
    run: customer-db-service
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      name: pgsql
  selector:
    app: customer-db